const alumnograduacion_def_tests = [
  // LOGIN - ADD
  {
    entidad: "alumnograduacion",
    campo: "login",
    numero_definicion: 1,
    descripcion: "Comprobar longitud mínima de login",
    accion: "ADD",
    resultado_esperado: "LOGIN_MIN_SIZE_KO",
    respuesta:
      "Error de longitud del login, debe contener al menos 4 carácteres.",
  },
  {
    entidad: "alumnograduacion",
    campo: "login",
    numero_definicion: 2,
    descripcion: "Comprobar longitud máxima de login",
    accion: "ADD",
    resultado_esperado: "LOGIN_MAX_SIZE_KO",
    respuesta:
      "Error de longitud del login, puede contener como mucho 15 carácteres.",
  },
  {
    entidad: "alumnograduacion",
    campo: "login",
    numero_definicion: 3,
    descripcion: "Comprobar formato de login",
    accion: "ADD",
    resultado_esperado: "LOGIN_FORMAT_KO",
    respuesta:
      "Error de formato del login, no puede contener carácteres especiales o numéricos.",
  },
  {
    entidad: "alumnograduacion",
    campo: "login",
    numero_definicion: 4,
    descripcion: "Añadir login válido",
    accion: "ADD",
    resultado_esperado: true,
    respuesta: "Login es correcto.",
  },
  // LOGIN - EDIT
  {
    entidad: "alumnograduacion",
    campo: "login",
    numero_definicion: 5,
    descripcion: "Comprobar longitud mínima de login",
    accion: "EDIT",
    resultado_esperado: "LOGIN_MIN_SIZE_KO",
    respuesta:
      "Error de longitud del login, debe contener al menos 4 carácteres.",
  },
  {
    entidad: "alumnograduacion",
    campo: "login",
    numero_definicion: 6,
    descripcion: "Comprobar longitud máxima de login",
    accion: "EDIT",
    resultado_esperado: "LOGIN_MAX_SIZE_KO",
    respuesta:
      "Error de longitud del login, puede contener como mucho 15 carácteres.",
  },
  {
    entidad: "alumnograduacion",
    campo: "login",
    numero_definicion: 7,
    descripcion: "Comprobar formato de login",
    accion: "EDIT",
    resultado_esperado: "LOGIN_FORMAT_KO",
    respuesta:
      "Error de formato del login, no puede contener carácteres especiales o numéricos.",
  },
  {
    entidad: "alumnograduacion",
    campo: "login",
    numero_definicion: 8,
    descripcion: "Editar login válido",
    accion: "EDIT",
    resultado_esperado: true,
    respuesta: "Login permitido al editar.",
  },
  {
    entidad: "alumnograduacion",
    campo: "login",
    numero_definicion: 9,
    descripcion: "Editar login válido (vacío)",
    accion: "EDIT",
    resultado_esperado: true,
    respuesta: "Login vacío permitido al editar.",
  },
  // LOGIN - SEARCH
  {
    entidad: "alumnograduacion",
    campo: "login",
    numero_definicion: 10,
    descripcion: "Buscar por login vacío",
    accion: "SEARCH",
    resultado_esperado: true,
    respuesta: "Login vacío permitido al buscar",
  },
  {
    entidad: "alumnograduacion",
    campo: "login",
    numero_definicion: 11,
    descripcion: "Buscar por login con tamaño máximo",
    accion: "SEARCH",
    resultado_esperado: "LOGIN_MAX_SIZE_KO",
    respuesta:
      "Error de tamaño máximo de login en búsqueda, login no puede tener más de 15 carácteres.",
  },
  {
    entidad: "alumnograduacion",
    campo: "login",
    numero_definicion: 12,
    descripcion: "Buscar por login con formato incorrecto",
    accion: "SEARCH",
    resultado_esperado: "LOGIN_FORMAT_KO",
    respuesta: "Error de formato en búsqueda, login con caracteres no válidos.",
  },
  {
    entidad: "alumnograduacion",
    campo: "login",
    numero_definicion: 10,
    descripcion: "Buscar por login",
    accion: "SEARCH",
    resultado_esperado: true,
    respuesta: "Login válido al buscar",
  },
  // PASSWORD - ADD
  {
    entidad: "alumnograduacion",
    campo: "password",
    numero_definicion: 13,
    descripcion: "Comprobar longitud mínima de password",
    accion: "ADD",
    resultado_esperado: "PASSWORD_MIN_SIZE_KO",
    respuesta:
      "Error de longitud de password, debe contener al menos 8 carácteres.",
  },
  {
    entidad: "alumnograduacion",
    campo: "password",
    numero_definicion: 14,
    descripcion: "Comprobar longitud máxima de password",
    accion: "ADD",
    resultado_esperado: "PASSWORD_MAX_SIZE_KO",
    respuesta:
      "Error de longitud de password, puede contener como mucho 64 carácteres.",
  },
  {
    entidad: "alumnograduacion",
    campo: "password",
    numero_definicion: 15,
    descripcion: "Comprobar formato incorrecto de password",
    accion: "ADD",
    resultado_esperado: "PASSWORD_FORMAT_KO",
    respuesta:
      "Error de formato de password, solo puede contener letras y espacios sin acentos ni ñ.",
  },
  {
    entidad: "alumnograduacion",
    campo: "password",
    numero_definicion: 16,
    descripcion: "Añadir password válida",
    accion: "ADD",
    resultado_esperado: true,
    respuesta: "Password es correcta.",
  },
  // PASSWORD - EDIT
  {
    entidad: "alumnograduacion",
    campo: "password",
    numero_definicion: 17,
    descripcion: "Editar password vacía (válido)",
    accion: "EDIT",
    resultado_esperado: true,
    respuesta: "Password vacía permitida en edición.",
  },
  {
    entidad: "alumnograduacion",
    campo: "password",
    numero_definicion: 18,
    descripcion: "Comprobar tamaño mínimo de editado de password",
    accion: "EDIT",
    resultado_esperado: "PASSWORD_MIN_SIZE_KO",
    respuesta:
      "Error de longitud de password, debe contener al menos 8 carácteres.",
  },
  {
    entidad: "alumnograduacion",
    campo: "password",
    numero_definicion: 19,
    descripcion: "Comprobar tamaño máximo de editado de password",
    accion: "EDIT",
    resultado_esperado: "PASSWORD_MAX_SIZE_KO",
    respuesta:
      "Error de longitud de password, puede contener como mucho 64 carácteres.",
  },
  {
    entidad: "alumnograduacion",
    campo: "password",
    numero_definicion: 20,
    descripcion: "Comprobar formato de editado de password",
    accion: "EDIT",
    resultado_esperado: "PASSWORD_FORMAT_KO",
    respuesta:
      "Error de formato de password, solo puede contener letras y espacios sin acentos ni ñ.",
  },
  // PASSWORD - SEARCH
  {
    entidad: "alumnograduacion",
    campo: "password",
    numero_definicion: 21,
    descripcion: "Buscar password vacía (válido)",
    accion: "SEARCH",
    resultado_esperado: true,
    respuesta: "Password vacía permitida en búsqueda.",
  },
  {
    entidad: "alumnograduacion",
    campo: "password",
    numero_definicion: 22,
    descripcion: "Comprobar tamaño máximo en búsqueda de password",
    accion: "SEARCH",
    resultado_esperado: "PASSWORD_MAX_SIZE_KO",
    respuesta:
      "Error de longitud de password, puede contener como mucho 64 carácteres.",
  },
  {
    entidad: "alumnograduacion",
    campo: "password",
    numero_definicion: 23,
    descripcion: "Comprobar formato en búsqueda de password",
    accion: "SEARCH",
    resultado_esperado: "PASSWORD_FORMAT_KO",
    respuesta:
      "Error de formato de password, solo puede contener letras y espacios sin acentos ni ñ.",
  },
  {
    entidad: "alumnograduacion",
    campo: "password",
    numero_definicion: 24,
    descripcion: "Buscar password válida",
    accion: "SEARCH",
    resultado_esperado: true,
    respuesta: "Password válida en búsqueda.",
  },
  // NOMBRE - ADD
  {
    entidad: "alumnograduacion",
    campo: "nombre",
    numero_definicion: 25,
    descripcion: "Comprobar longitud mínima de nombre",
    accion: "ADD",
    resultado_esperado: "NOMBRE_MIN_SIZE_KO",
    respuesta:
      "Error de longitud del nombre, debe contener al menos 2 caracteres.",
  },
  {
    entidad: "alumnograduacion",
    campo: "nombre",
    numero_definicion: 26,
    descripcion: "Comprobar longitud máxima de nombre",
    accion: "ADD",
    resultado_esperado: "NOMBRE_MAX_SIZE_KO",
    respuesta:
      "Error de longitud del nombre, puede contener como mucho 25 caracteres.",
  },
  {
    entidad: "alumnograduacion",
    campo: "nombre",
    numero_definicion: 27,
    descripcion: "Comprobar formato incorrecto de nombre",
    accion: "ADD",
    resultado_esperado: "NOMBRE_FORMAT_KO",
    respuesta:
      "Error de formato del nombre, solo puede contener letras, espacios, acentos y ñ.",
  },
  {
    entidad: "alumnograduacion",
    campo: "nombre",
    numero_definicion: 28,
    descripcion: "Añadir nombre válido",
    accion: "ADD",
    resultado_esperado: true,
    respuesta: "Nombre es correcto.",
  },

  // NOMBRE - EDIT
  {
    entidad: "alumnograduacion",
    campo: "nombre",
    numero_definicion: 29,
    descripcion: "Comprobar longitud mínima de nombre",
    accion: "EDIT",
    resultado_esperado: "NOMBRE_MIN_SIZE_KO",
    respuesta:
      "Error de longitud del nombre, debe contener al menos 2 caracteres.",
  },
  {
    entidad: "alumnograduacion",
    campo: "nombre",
    numero_definicion: 30,
    descripcion: "Comprobar longitud máxima de nombre",
    accion: "EDIT",
    resultado_esperado: "NOMBRE_MAX_SIZE_KO",
    respuesta:
      "Error de longitud del nombre, puede contener como mucho 25 caracteres.",
  },
  {
    entidad: "alumnograduacion",
    campo: "nombre",
    numero_definicion: 31,
    descripcion: "Comprobar formato incorrecto de nombre",
    accion: "EDIT",
    resultado_esperado: "NOMBRE_FORMAT_KO",
    respuesta:
      "Error de formato del nombre, solo puede contener letras, espacios, acentos y ñ.",
  },
  {
    entidad: "alumnograduacion",
    campo: "nombre",
    numero_definicion: 32,
    descripcion: "Editar nombre válido",
    accion: "EDIT",
    resultado_esperado: true,
    respuesta: "Nombre permitido al editar.",
  },
  {
    entidad: "alumnograduacion",
    campo: "nombre",
    numero_definicion: 33,
    descripcion: "Editar nombre vacío",
    accion: "EDIT",
    resultado_esperado: true,
    respuesta: "Nombre vacío permitido al editar.",
  },

  // NOMBRE - SEARCH
  {
    entidad: "alumnograduacion",
    campo: "nombre",
    numero_definicion: 34,
    descripcion: "Buscar por nombre vacío",
    accion: "SEARCH",
    resultado_esperado: true,
    respuesta: "Nombre vacío permitido al buscar.",
  },
  {
    entidad: "alumnograduacion",
    campo: "nombre",
    numero_definicion: 35,
    descripcion: "Buscar por nombre con tamaño máximo",
    accion: "SEARCH",
    resultado_esperado: "NOMBRE_MAX_SIZE_KO",
    respuesta:
      "Error de tamaño máximo de nombre en búsqueda, no puede tener más de 25 caracteres.",
  },
  {
    entidad: "alumnograduacion",
    campo: "nombre",
    numero_definicion: 36,
    descripcion: "Buscar por nombre con formato incorrecto",
    accion: "SEARCH",
    resultado_esperado: "NOMBRE_FORMAT_KO",
    respuesta:
      "Error de formato en búsqueda, nombre con caracteres no válidos.",
  },
  {
    entidad: "alumnograduacion",
    campo: "nombre",
    numero_definicion: 37,
    descripcion: "Buscar por nombre",
    accion: "SEARCH",
    resultado_esperado: true,
    respuesta: "Nombre válido al buscar.",
  },
  // APELLIDOS - ADD
  {
    entidad: "alumnograduacion",
    campo: "apellidos",
    numero_definicion: 38,
    descripcion: "Comprobar longitud mínima de apellidos",
    accion: "ADD",
    resultado_esperado: "APELLIDOS_MIN_SIZE_KO",
    respuesta:
      "Error de longitud de apellidos, debe contener al menos 2 caracteres.",
  },
  {
    entidad: "alumnograduacion",
    campo: "apellidos",
    numero_definicion: 39,
    descripcion: "Comprobar longitud máxima de apellidos",
    accion: "ADD",
    resultado_esperado: "APELLIDOS_MAX_SIZE_KO",
    respuesta:
      "Error de longitud de apellidos, puede contener como mucho 35 caracteres.",
  },
  {
    entidad: "alumnograduacion",
    campo: "apellidos",
    numero_definicion: 40,
    descripcion: "Comprobar formato incorrecto de apellidos",
    accion: "ADD",
    resultado_esperado: "APELLIDOS_FORMAT_KO",
    respuesta:
      "Error de formato de apellidos, solo puede contener letras, espacios, acentos y ñ.",
  },
  {
    entidad: "alumnograduacion",
    campo: "apellidos",
    numero_definicion: 41,
    descripcion: "Añadir apellidos válidos",
    accion: "ADD",
    resultado_esperado: true,
    respuesta: "Apellidos son correctos.",
  },

  // APELLIDOS - EDIT
  {
    entidad: "alumnograduacion",
    campo: "apellidos",
    numero_definicion: 42,
    descripcion: "Comprobar longitud mínima de apellidos",
    accion: "EDIT",
    resultado_esperado: "APELLIDOS_MIN_SIZE_KO",
    respuesta:
      "Error de longitud de apellidos, debe contener al menos 2 caracteres.",
  },
  {
    entidad: "alumnograduacion",
    campo: "apellidos",
    numero_definicion: 43,
    descripcion: "Comprobar longitud máxima de apellidos",
    accion: "EDIT",
    resultado_esperado: "APELLIDOS_MAX_SIZE_KO",
    respuesta:
      "Error de longitud de apellidos, puede contener como mucho 35 caracteres.",
  },
  {
    entidad: "alumnograduacion",
    campo: "apellidos",
    numero_definicion: 44,
    descripcion: "Comprobar formato incorrecto de apellidos",
    accion: "EDIT",
    resultado_esperado: "APELLIDOS_FORMAT_KO",
    respuesta:
      "Error de formato de apellidos, solo puede contener letras, espacios, acentos y ñ.",
  },
  {
    entidad: "alumnograduacion",
    campo: "apellidos",
    numero_definicion: 45,
    descripcion: "Editar apellidos válidos",
    accion: "EDIT",
    resultado_esperado: true,
    respuesta: "Apellidos permitidos al editar.",
  },
  {
    entidad: "alumnograduacion",
    campo: "apellidos",
    numero_definicion: 46,
    descripcion: "Editar apellidos vacíos",
    accion: "EDIT",
    resultado_esperado: true,
    respuesta: "Apellidos vacíos permitidos al editar.",
  },

  // APELLIDOS - SEARCH
  {
    entidad: "alumnograduacion",
    campo: "apellidos",
    numero_definicion: 47,
    descripcion: "Buscar por apellidos vacíos",
    accion: "SEARCH",
    resultado_esperado: true,
    respuesta: "Apellidos vacíos permitidos al buscar.",
  },
  {
    entidad: "alumnograduacion",
    campo: "apellidos",
    numero_definicion: 48,
    descripcion: "Buscar por apellidos con tamaño máximo",
    accion: "SEARCH",
    resultado_esperado: "APELLIDOS_MAX_SIZE_KO",
    respuesta:
      "Error de tamaño máximo de apellidos en búsqueda, no puede tener más de 35 caracteres.",
  },
  {
    entidad: "alumnograduacion",
    campo: "apellidos",
    numero_definicion: 49,
    descripcion: "Buscar por apellidos con formato incorrecto",
    accion: "SEARCH",
    resultado_esperado: "APELLIDOS_FORMAT_KO",
    respuesta:
      "Error de formato en búsqueda, apellidos con caracteres no válidos.",
  },
  {
    entidad: "alumnograduacion",
    campo: "apellidos",
    numero_definicion: 50,
    descripcion: "Buscar por apellidos válidos (no vacíos)",
    accion: "SEARCH",
    resultado_esperado: true,
    respuesta: "Apellidos válidos permitidos al buscar.",
  },
  // TITULACION - ADD
  {
    entidad: "alumnograduacion",
    campo: "titulacion",
    numero_definicion: 51,
    descripcion: "Comprobar titulacion vacía al añadir",
    accion: "ADD",
    resultado_esperado: "TITULACION_EMPTY_KO",
    respuesta: "Error, la titulación no puede estar vacía al añadir.",
  },
  {
    entidad: "alumnograduacion",
    campo: "titulacion",
    numero_definicion: 52,
    descripcion: "Comprobar titulacion con valor no permitido",
    accion: "ADD",
    resultado_esperado: "TITULACION_INVALID_KO",
    respuesta:
      "Error, valor de titulación no permitido. Valores válidos: GREI, GRIA, MEI, MIA, PCEO.",
  },
  {
    entidad: "alumnograduacion",
    campo: "titulacion",
    numero_definicion: 53,
    descripcion: "Añadir titulacion válida",
    accion: "ADD",
    resultado_esperado: true,
    respuesta: "Titulación es correcta.",
  },

  // TITULACION - EDIT
  {
    entidad: "alumnograduacion",
    campo: "titulacion",
    numero_definicion: 54,
    descripcion: "Comprobar titulacion con valor no permitido al editar",
    accion: "EDIT",
    resultado_esperado: "TITULACION_INVALID_KO",
    respuesta:
      "Error, valor de titulación no permitido al editar. Valores válidos: GREI, GRIA, MEI, MIA, PCEO.",
  },
  {
    entidad: "alumnograduacion",
    campo: "titulacion",
    numero_definicion: 55,
    descripcion: "Editar titulacion válida",
    accion: "EDIT",
    resultado_esperado: true,
    respuesta: "Titulación válida permitida al editar.",
  },
  {
    entidad: "alumnograduacion",
    campo: "titulacion",
    numero_definicion: 56,
    descripcion: "Editar titulacion vacía",
    accion: "EDIT",
    resultado_esperado: true,
    respuesta: "Titulación vacía permitida al editar.",
  },
  // TITULACION - SEARCH
  {
    entidad: "alumnograduacion",
    campo: "titulacion",
    numero_definicion: 57,
    descripcion: "Buscar por titulacion vacía",
    accion: "SEARCH",
    resultado_esperado: true,
    respuesta: "Titulación vacía permitida al buscar.",
  },
  {
    entidad: "alumnograduacion",
    campo: "titulacion",
    numero_definicion: 58,
    descripcion: "Buscar por titulacion con tamaño máximo",
    accion: "SEARCH",
    resultado_esperado: "TITULACION_MAX_SIZE_KO",
    respuesta:
      "Error de tamaño máximo de titulación, no puede se mayor de 4 caracteres.",
  },
  // DNI - ADD
  {
    entidad: "alumnograduacion",
    campo: "dni",
    numero_definicion: 59,
    descripcion: "Comprobar DNI vacío al añadir",
    accion: "ADD",
    resultado_esperado: "DNI_VACIO_KO",
    respuesta: "Error, el DNI no puede estar vacío al añadir.",
  },
  {
    entidad: "alumnograduacion",
    campo: "dni",
    numero_definicion: 60,
    descripcion: "Comprobar formato incorrecto de DNI (estructura inválida)",
    accion: "ADD",
    resultado_esperado: "DNI_FORMATO_KO",
    respuesta:
      "Error, el formato del DNI es incorrecto. Debe tener 8 números seguidos de una letra válida.",
  },
  {
    entidad: "alumnograduacion",
    campo: "dni",
    numero_definicion: 61,
    descripcion:
      "Comprobar formato incorrecto de NIE (letra inicial no válida)",
    accion: "ADD",
    resultado_esperado: "NIE_FORMATO_KO",
    respuesta:
      "Error, el formato del NIE es incorrecto. Debe comenzar por X, Y o Z, seguido de 7 números y una letra válida.",
  },
  {
    entidad: "alumnograduacion",
    campo: "dni",
    numero_definicion: 62,
    descripcion: "Comprobar letra no válida para número de DNI/NIE",
    accion: "ADD",
    resultado_esperado: "DNI_LETRA_KO",
    respuesta:
      "Error, la letra del DNI/NIE no corresponde al número introducido.",
  },
  {
    entidad: "alumnograduacion",
    campo: "dni",
    numero_definicion: 63,
    descripcion: "Añadir DNI válido (formato correcto y letra válida)",
    accion: "ADD",
    resultado_esperado: true,
    respuesta: "DNI/NIE correcto.",
  },

  // DNI - EDIT
  {
    entidad: "alumnograduacion",
    campo: "dni",
    numero_definicion: 64,
    descripcion: "Comprobar formato incorrecto de DNI al editar",
    accion: "EDIT",
    resultado_esperado: "DNI_FORMATO_KO",
    respuesta: "Error, el formato del DNI/NIE es incorrecto al editar.",
  },
  {
    entidad: "alumnograduacion",
    campo: "dni",
    numero_definicion: 65,
    descripcion: "Editar DNI válido",
    accion: "EDIT",
    resultado_esperado: true,
    respuesta: "DNI/NIE válido permitido al editar.",
  },
  {
    entidad: "alumnograduacion",
    campo: "dni",
    numero_definicion: 66,
    descripcion: "Editar DNI vacío",
    accion: "EDIT",
    resultado_esperado: true,
    respuesta: "DNI vacío permitido al editar.",
  },

  // DNI - SEARCH
  {
    entidad: "alumnograduacion",
    campo: "dni",
    numero_definicion: 67,
    descripcion: "Buscar por DNI vacío",
    accion: "SEARCH",
    resultado_esperado: true,
    respuesta: "DNI vacío permitido al buscar.",
  },
  {
    entidad: "alumnograduacion",
    campo: "dni",
    numero_definicion: 68,
    descripcion: "Buscar por DNI con formato incorrecto",
    accion: "SEARCH",
    resultado_esperado: "DNI_FORMATO_KO",
    respuesta: "Error, formato de DNI/NIE no válido en búsqueda.",
  },
  {
    entidad: "alumnograduacion",
    campo: "dni",
    numero_definicion: 69,
    descripcion: "Buscar por DNI válido (no vacío)",
    accion: "SEARCH",
    resultado_esperado: true,
    respuesta: "DNI/NIE válido permitido al buscar.",
  },
  // TELEFONO - ADD
  {
    entidad: "alumnograduacion",
    campo: "telefono",
    numero_definicion: 70,
    descripcion: "Comprobar teléfono vacío al añadir",
    accion: "ADD",
    resultado_esperado: "TELEFONO_VACIO_KO",
    respuesta: "Error, el teléfono no puede estar vacío al añadir.",
  },
  {
    entidad: "alumnograduacion",
    campo: "telefono",
    numero_definicion: 71,
    descripcion:
      "Comprobar longitud incorrecta de teléfono (menos de 9 dígitos)",
    accion: "ADD",
    resultado_esperado: "TELEFONO_MIN_SIZE_KO",
    respuesta: "Error, el teléfono debe tener exactamente 9 dígitos.",
  },
  {
    entidad: "alumnograduacion",
    campo: "telefono",
    numero_definicion: 72,
    descripcion: "Comprobar longitud incorrecta de teléfono (más de 9 dígitos)",
    accion: "ADD",
    resultado_esperado: "TELEFONO_MAX_SIZE_KO",
    respuesta: "Error, el teléfono debe tener exactamente 9 dígitos.",
  },
  {
    entidad: "alumnograduacion",
    campo: "telefono",
    numero_definicion: 73,
    descripcion:
      "Comprobar formato incorrecto de teléfono (contiene letras o símbolos)",
    accion: "ADD",
    resultado_esperado: "TELEFONO_FORMAT_KO",
    respuesta: "Error, el teléfono solo puede contener números (0-9).",
  },
  {
    entidad: "alumnograduacion",
    campo: "telefono",
    numero_definicion: 74,
    descripcion: "Añadir teléfono válido",
    accion: "ADD",
    resultado_esperado: true,
    respuesta: "Teléfono correcto.",
  },
  // TELEFONO - EDIT
  {
    entidad: "alumnograduacion",
    campo: "telefono",
    numero_definicion: 75,
    descripcion: "Comprobar formato incorrecto de teléfono al editar",
    accion: "EDIT",
    resultado_esperado: "TELEFONO_FORMAT_KO",
    respuesta:
      "Error, formato de teléfono incorrecto al editar. Solo números permitidos.",
  },
  {
    entidad: "alumnograduacion",
    campo: "telefono",
    numero_definicion: 76,
    descripcion: "Editar teléfono válido",
    accion: "EDIT",
    resultado_esperado: true,
    respuesta: "Teléfono válido permitido al editar.",
  },
  {
    entidad: "alumnograduacion",
    campo: "telefono",
    numero_definicion: 77,
    descripcion: "Editar teléfono vacío",
    accion: "EDIT",
    resultado_esperado: true,
    respuesta: "Teléfono vacío permitido al editar.",
  },

  // TELEFONO - SEARCH
  {
    entidad: "alumnograduacion",
    campo: "telefono",
    numero_definicion: 78,
    descripcion: "Buscar por teléfono vacío",
    accion: "SEARCH",
    resultado_esperado: true,
    respuesta: "Teléfono vacío permitido al buscar.",
  },
  {
    entidad: "alumnograduacion",
    campo: "telefono",
    numero_definicion: 79,
    descripcion: "Buscar por teléfono con formato incorrecto",
    accion: "SEARCH",
    resultado_esperado: "TELEFONO_FORMAT_KO",
    respuesta: "Error, formato de teléfono incorrecto en búsqueda.",
  },
  {
    entidad: "alumnograduacion",
    campo: "telefono",
    numero_definicion: 80,
    descripcion: "Buscar por teléfono válido (no vacío)",
    accion: "SEARCH",
    resultado_esperado: true,
    respuesta: "Teléfono válido permitido al buscar.",
  },
  // DIRECCION - ADD
  {
    entidad: "alumnograduacion",
    campo: "direccion",
    numero_definicion: 81,
    descripcion: "Comprobar dirección vacía al añadir",
    accion: "ADD",
    resultado_esperado: "DIRECCION_VACIA_KO",
    respuesta: "Error, la dirección no puede estar vacía al añadir.",
  },
  {
    entidad: "alumnograduacion",
    campo: "direccion",
    numero_definicion: 82,
    descripcion: "Comprobar longitud máxima de dirección",
    accion: "ADD",
    resultado_esperado: "DIRECCION_MAX_SIZE_KO",
    respuesta: "Error, la dirección no puede superar los 100 caracteres.",
  },
  {
    entidad: "alumnograduacion",
    campo: "direccion",
    numero_definicion: 83,
    descripcion:
      "Comprobar formato incorrecto de dirección (caracteres no permitidos)",
    accion: "ADD",
    resultado_esperado: "DIRECCION_FORMAT_KO",
    respuesta:
      "Error, la dirección solo puede contener letras, números, espacios, acentos y ñ.",
  },
  {
    entidad: "alumnograduacion",
    campo: "direccion",
    numero_definicion: 84,
    descripcion: "Añadir dirección válida",
    accion: "ADD",
    resultado_esperado: true,
    respuesta: "Dirección correcta.",
  },

  // DIRECCION - EDIT
  {
    entidad: "alumnograduacion",
    campo: "direccion",
    numero_definicion: 85,
    descripcion: "Comprobar longitud máxima de dirección al editar",
    accion: "EDIT",
    resultado_esperado: "DIRECCION_MAX_SIZE_KO",
    respuesta:
      "Error, la dirección no puede superar los 100 caracteres al editar.",
  },
  {
    entidad: "alumnograduacion",
    campo: "direccion",
    numero_definicion: 86,
    descripcion: "Comprobar formato incorrecto de dirección al editar",
    accion: "EDIT",
    resultado_esperado: "DIRECCION_FORMAT_KO",
    respuesta:
      "Error, formato de dirección incorrecto al editar. Solo letras, números, acentos y espacios.",
  },
  {
    entidad: "alumnograduacion",
    campo: "direccion",
    numero_definicion: 87,
    descripcion: "Editar dirección válida",
    accion: "EDIT",
    resultado_esperado: true,
    respuesta: "Dirección válida permitida al editar.",
  },
  {
    entidad: "alumnograduacion",
    campo: "direccion",
    numero_definicion: 88,
    descripcion: "Editar dirección vacía",
    accion: "EDIT",
    resultado_esperado: true,
    respuesta: "Dirección vacía permitida al editar.",
  },

  // DIRECCION - SEARCH
  {
    entidad: "alumnograduacion",
    campo: "direccion",
    numero_definicion: 89,
    descripcion: "Buscar por dirección vacía",
    accion: "SEARCH",
    resultado_esperado: true,
    respuesta: "Dirección vacía permitida al buscar.",
  },
  {
    entidad: "alumnograduacion",
    campo: "direccion",
    numero_definicion: 90,
    descripcion: "Buscar por dirección con tamaño máximo",
    accion: "SEARCH",
    resultado_esperado: "DIRECCION_MAX_SIZE_KO",
    respuesta:
      "Error, la dirección no puede superar los 100 caracteres en búsqueda.",
  },
  {
    entidad: "alumnograduacion",
    campo: "direccion",
    numero_definicion: 91,
    descripcion: "Buscar por dirección con formato incorrecto",
    accion: "SEARCH",
    resultado_esperado: "DIRECCION_FORMAT_KO",
    respuesta: "Error, formato de dirección incorrecto en búsqueda.",
  },
  {
    entidad: "alumnograduacion",
    campo: "direccion",
    numero_definicion: 92,
    descripcion: "Buscar por dirección válida (no vacía)",
    accion: "SEARCH",
    resultado_esperado: true,
    respuesta: "Dirección válida permitida al buscar.",
  },
  // EMAIL - ADD
  {
    entidad: "alumnograduacion",
    campo: "email",
    numero_definicion: 93,
    descripcion: "Comprobar email vacío al añadir",
    accion: "ADD",
    resultado_esperado: "EMAIL_VACIO_KO",
    respuesta: "Error, el email no puede estar vacío al añadir.",
  },
  {
    entidad: "alumnograduacion",
    campo: "email",
    numero_definicion: 94,
    descripcion: "Comprobar longitud máxima de email",
    accion: "ADD",
    resultado_esperado: "EMAIL_MAX_SIZE_KO",
    respuesta: "Error, el email no puede superar los 40 caracteres.",
  },
  {
    entidad: "alumnograduacion",
    campo: "email",
    numero_definicion: 95,
    descripcion: "Comprobar formato incorrecto de email",
    accion: "ADD",
    resultado_esperado: "EMAIL_FORMAT_KO",
    respuesta:
      "Error, el formato del email es incorrecto. Debe tener el formato usuario@dominio.ext.",
  },
  {
    entidad: "alumnograduacion",
    campo: "email",
    numero_definicion: 96,
    descripcion: "Añadir email válido",
    accion: "ADD",
    resultado_esperado: true,
    respuesta: "Email correcto.",
  },

  // EMAIL - EDIT
  {
    entidad: "alumnograduacion",
    campo: "email",
    numero_definicion: 97,
    descripcion: "Comprobar longitud máxima de email al editar",
    accion: "EDIT",
    resultado_esperado: "EMAIL_MAX_SIZE_KO",
    respuesta: "Error, el email no puede superar los 40 caracteres al editar.",
  },
  {
    entidad: "alumnograduacion",
    campo: "email",
    numero_definicion: 98,
    descripcion: "Comprobar formato incorrecto de email al editar",
    accion: "EDIT",
    resultado_esperado: "EMAIL_FORMAT_KO",
    respuesta: "Error, formato de email incorrecto al editar.",
  },
  {
    entidad: "alumnograduacion",
    campo: "email",
    numero_definicion: 99,
    descripcion: "Editar email válido",
    accion: "EDIT",
    resultado_esperado: true,
    respuesta: "Email válido permitido al editar.",
  },
  {
    entidad: "alumnograduacion",
    campo: "email",
    numero_definicion: 100,
    descripcion: "Editar email vacío",
    accion: "EDIT",
    resultado_esperado: true,
    respuesta: "Email vacío permitido al editar.",
  },

  // EMAIL - SEARCH
  {
    entidad: "alumnograduacion",
    campo: "email",
    numero_definicion: 101,
    descripcion: "Buscar por email vacío",
    accion: "SEARCH",
    resultado_esperado: true,
    respuesta: "Email vacío permitido al buscar.",
  },
  {
    entidad: "alumnograduacion",
    campo: "email",
    numero_definicion: 102,
    descripcion: "Buscar por email con tamaño máximo",
    accion: "SEARCH",
    resultado_esperado: "EMAIL_MAX_SIZE_KO",
    respuesta:
      "Error, el email no puede superar los 40 caracteres en búsqueda.",
  },
  {
    entidad: "alumnograduacion",
    campo: "email",
    numero_definicion: 103,
    descripcion: "Buscar por email con formato incorrecto",
    accion: "SEARCH",
    resultado_esperado: "EMAIL_FORMAT_KO",
    respuesta: "Error, formato de email incorrecto en búsqueda.",
  },
  {
    entidad: "alumnograduacion",
    campo: "email",
    numero_definicion: 104,
    descripcion: "Buscar por email válido (no vacío)",
    accion: "SEARCH",
    resultado_esperado: true,
    respuesta: "Email válido permitido al buscar.",
  },
  // FOTOACTO - ADD
  {
    entidad: "alumnograduacion",
    campo: "fotoacto",
    numero_definicion: 105,
    descripcion: "Comprobar fotoacto vacío al añadir",
    accion: "ADD",
    resultado_esperado: "FOTOACTO_VACIO_KO",
    respuesta:
      "Error, el nombre del archivo de la foto no puede estar vacío al añadir.",
  },
  {
    entidad: "alumnograduacion",
    campo: "fotoacto",
    numero_definicion: 106,
    descripcion: "Comprobar longitud mínima de fotoacto",
    accion: "ADD",
    resultado_esperado: "FOTOACTO_MIN_SIZE_KO",
    respuesta: "Error, el nombre de la foto debe tener al menos 7 caracteres.",
  },
  {
    entidad: "alumnograduacion",
    campo: "fotoacto",
    numero_definicion: 107,
    descripcion: "Comprobar longitud máxima de fotoacto",
    accion: "ADD",
    resultado_esperado: "FOTOACTO_MAX_SIZE_KO",
    respuesta:
      "Error, el nombre de la foto no puede superar los 100 caracteres.",
  },
  {
    entidad: "alumnograduacion",
    campo: "fotoacto",
    numero_definicion: 108,
    descripcion:
      "Comprobar formato incorrecto de fotoacto (caracteres no permitidos o espacios)",
    accion: "ADD",
    resultado_esperado: "FOTOACTO_FORMAT_KO",
    respuesta:
      "Error, el nombre del archivo solo puede contener letras y puntos, sin espacios, acentos ni ñ.",
  },
  {
    entidad: "alumnograduacion",
    campo: "fotoacto",
    numero_definicion: 109,
    descripcion: "Comprobar extensión incorrecta de fotoacto (no .jpg)",
    accion: "ADD",
    resultado_esperado: "FOTOACTO_EXTENSION_KO",
    respuesta: "Error, el archivo de la foto debe tener extensión .jpg.",
  },
  {
    entidad: "alumnograduacion",
    campo: "fotoacto",
    numero_definicion: 110,
    descripcion: "Comprobar tamaño de fichero superior a 2MB",
    accion: "ADD",
    resultado_esperado: "FOTOACTO_TAMANO_KO",
    respuesta: "Error, el archivo de la foto no puede superar los 2MB.",
  },
  {
    entidad: "alumnograduacion",
    campo: "fotoacto",
    numero_definicion: 111,
    descripcion: "Añadir fotoacto válido (.jpg y tamaño correcto)",
    accion: "ADD",
    resultado_esperado: true,
    respuesta: "Fotoacto válida y aceptada.",
  },

  // FOTOACTO - EDIT
  {
    entidad: "alumnograduacion",
    campo: "fotoacto",
    numero_definicion: 112,
    descripcion: "Comprobar formato incorrecto de fotoacto al editar",
    accion: "EDIT",
    resultado_esperado: "FOTOACTO_FORMAT_KO",
    respuesta: "Error, formato de nombre de foto no válido al editar.",
  },
  {
    entidad: "alumnograduacion",
    campo: "fotoacto",
    numero_definicion: 113,
    descripcion: "Comprobar extensión incorrecta de fotoacto al editar",
    accion: "EDIT",
    resultado_esperado: "FOTOACTO_EXTENSION_KO",
    respuesta: "Error, solo se permiten archivos .jpg al editar.",
  },
  {
    entidad: "alumnograduacion",
    campo: "fotoacto",
    numero_definicion: 114,
    descripcion: "Comprobar tamaño de fichero superior a 2MB al editar",
    accion: "EDIT",
    resultado_esperado: "FOTOACTO_TAMANO_KO",
    respuesta: "Error, el archivo de foto supera los 2MB al editar.",
  },
  {
    entidad: "alumnograduacion",
    campo: "fotoacto",
    numero_definicion: 115,
    descripcion: "Editar fotoacto válido",
    accion: "EDIT",
    resultado_esperado: true,
    respuesta: "Fotoacto válida permitida al editar.",
  },
  {
    entidad: "alumnograduacion",
    campo: "fotoacto",
    numero_definicion: 116,
    descripcion: "Editar fotoacto vacío",
    accion: "EDIT",
    resultado_esperado: true,
    respuesta: "Fotoacto vacío permitido al editar.",
  },

  // FOTOACTO - SEARCH
  {
    entidad: "alumnograduacion",
    campo: "fotoacto",
    numero_definicion: 117,
    descripcion: "Buscar por fotoacto vacío",
    accion: "SEARCH",
    resultado_esperado: true,
    respuesta: "Fotoacto vacío permitido al buscar.",
  },
  {
    entidad: "alumnograduacion",
    campo: "fotoacto",
    numero_definicion: 118,
    descripcion: "Buscar por fotoacto con tamaño máximo",
    accion: "SEARCH",
    resultado_esperado: "FOTOACTO_MAX_SIZE_KO",
    respuesta:
      "Error, el nombre de la foto no puede superar los 100 caracteres en búsqueda.",
  },
  {
    entidad: "alumnograduacion",
    campo: "fotoacto",
    numero_definicion: 119,
    descripcion: "Buscar por fotoacto con formato incorrecto",
    accion: "SEARCH",
    resultado_esperado: "FOTOACTO_FORMAT_KO",
    respuesta: "Error, formato de nombre de foto incorrecto en búsqueda.",
  },
  {
    entidad: "alumnograduacion",
    campo: "fotoacto",
    numero_definicion: 120,
    descripcion: "Buscar por fotoacto válido (no vacío)",
    accion: "SEARCH",
    resultado_esperado: true,
    respuesta: "Fotoacto válida permitida al buscar.",
  },
];

const alumnograduacion_tests_fields = [
  // LOGIN - ADD
  {
    entidad: "alumnograduacion",
    campo: "login",
    numero_definicion: 1,
    numero_prueba: 1,
    accion: "ADD",
    valor: "vis",
    codigo: "LOGIN_MIN_SIZE_KO",
  },
  {
    entidad: "alumnograduacion",
    campo: "login",
    numero_definicion: 2,
    numero_prueba: 1,
    accion: "ADD",
    valor: "visamitapeballito",
    codigo: "LOGIN_MAX_SIZE_KO",
  },
  {
    entidad: "alumnograduacion",
    campo: "login",
    numero_definicion: 3,
    numero_prueba: 1,
    accion: "ADD",
    valor: "1visamita@",
    codigo: "LOGIN_FORMAT_KO",
  },
  {
    entidad: "alumnograduacion",
    campo: "login",
    numero_definicion: 4,
    numero_prueba: 1,
    accion: "ADD",
    valor: "visama",
    codigo: true,
  },

  // LOGIN - EDIT
  {
    entidad: "alumnograduacion",
    campo: "login",
    numero_definicion: 5,
    numero_prueba: 1,
    accion: "EDIT",
    valor: "vis",
    codigo: "LOGIN_MIN_SIZE_KO",
  },
  {
    entidad: "alumnograduacion",
    campo: "login",
    numero_definicion: 6,
    numero_prueba: 1,
    accion: "EDIT",
    valor: "visamitapeballito",
    codigo: "LOGIN_MAX_SIZE_KO",
  },
  {
    entidad: "alumnograduacion",
    campo: "login",
    numero_definicion: 7,
    numero_prueba: 1,
    accion: "EDIT",
    valor: "1visamita@",
    codigo: "LOGIN_FORMAT_KO",
  },
  {
    entidad: "alumnograduacion",
    campo: "login",
    numero_definicion: 8,
    numero_prueba: 1,
    accion: "EDIT",
    valor: "visama",
    codigo: true,
  },
  {
    entidad: "alumnograduacion",
    campo: "login",
    numero_definicion: 9,
    numero_prueba: 1,
    accion: "EDIT",
    valor: "",
    codigo: true,
  },

  // LOGIN - SEARCH
  {
    entidad: "alumnograduacion",
    campo: "login",
    numero_definicion: 10,
    numero_prueba: 1,
    accion: "SEARCH",
    valor: "",
    codigo: true,
  },
  {
    entidad: "alumnograduacion",
    campo: "login",
    numero_definicion: 11,
    numero_prueba: 1,
    accion: "SEARCH",
    valor: "visamitapeballito",
    codigo: "LOGIN_MAX_SIZE_KO",
  },
  {
    entidad: "alumnograduacion",
    campo: "login",
    numero_definicion: 12,
    numero_prueba: 1,
    accion: "SEARCH",
    valor: "1visamita@",
    codigo: "LOGIN_FORMAT_KO",
  },
  {
    entidad: "alumnograduacion",
    campo: "login",
    numero_definicion: 10,
    numero_prueba: 2,
    accion: "SEARCH",
    valor: "visama",
    codigo: true,
  },

  // PASSWORD - ADD
  {
    entidad: "alumnograduacion",
    campo: "password",
    numero_definicion: 13,
    numero_prueba: 1,
    accion: "ADD",
    valor: "1234567",
    codigo: "PASSWORD_MIN_SIZE_KO",
  },
  {
    entidad: "alumnograduacion",
    campo: "password",
    numero_definicion: 14,
    numero_prueba: 1,
    accion: "ADD",
    valor: "a".repeat(65),
    codigo: "PASSWORD_MAX_SIZE_KO",
  },
  {
    entidad: "alumnograduacion",
    campo: "password",
    numero_definicion: 15,
    numero_prueba: 1,
    accion: "ADD",
    valor: "passw0rd!",
    codigo: "PASSWORD_FORMAT_KO",
  },
  {
    entidad: "alumnograduacion",
    campo: "password",
    numero_definicion: 16,
    numero_prueba: 1,
    accion: "ADD",
    valor: "PasswordSegura",
    codigo: true,
  },

  // PASSWORD - EDIT
  {
    entidad: "alumnograduacion",
    campo: "password",
    numero_definicion: 17,
    numero_prueba: 1,
    accion: "EDIT",
    valor: "",
    codigo: true,
  },
  {
    entidad: "alumnograduacion",
    campo: "password",
    numero_definicion: 18,
    numero_prueba: 1,
    accion: "EDIT",
    valor: "1234567",
    codigo: "PASSWORD_MIN_SIZE_KO",
  },
  {
    entidad: "alumnograduacion",
    campo: "password",
    numero_definicion: 19,
    numero_prueba: 1,
    accion: "EDIT",
    valor: "a".repeat(65),
    codigo: "PASSWORD_MAX_SIZE_KO",
  },
  {
    entidad: "alumnograduacion",
    campo: "password",
    numero_definicion: 20,
    numero_prueba: 1,
    accion: "EDIT",
    valor: "passw0rd!",
    codigo: "PASSWORD_FORMAT_KO",
  },

  // PASSWORD - SEARCH
  {
    entidad: "alumnograduacion",
    campo: "password",
    numero_definicion: 21,
    numero_prueba: 1,
    accion: "SEARCH",
    valor: "",
    codigo: true,
  },
  {
    entidad: "alumnograduacion",
    campo: "password",
    numero_definicion: 22,
    numero_prueba: 1,
    accion: "SEARCH",
    valor: "a".repeat(65),
    codigo: "PASSWORD_MAX_SIZE_KO",
  },
  {
    entidad: "alumnograduacion",
    campo: "password",
    numero_definicion: 23,
    numero_prueba: 1,
    accion: "SEARCH",
    valor: "passw0rd!",
    codigo: "PASSWORD_FORMAT_KO",
  },
  {
    entidad: "alumnograduacion",
    campo: "password",
    numero_definicion: 24,
    numero_prueba: 1,
    accion: "SEARCH",
    valor: "PasswordSegura",
    codigo: true,
  },

  // NOMBRE - ADD
  {
    entidad: "alumnograduacion",
    campo: "nombre",
    numero_definicion: 25,
    numero_prueba: 1,
    accion: "ADD",
    valor: "A",
    codigo: "NOMBRE_MIN_SIZE_KO",
  },
  {
    entidad: "alumnograduacion",
    campo: "nombre",
    numero_definicion: 26,
    numero_prueba: 1,
    accion: "ADD",
    valor: "A".repeat(26),
    codigo: "NOMBRE_MAX_SIZE_KO",
  },
  {
    entidad: "alumnograduacion",
    campo: "nombre",
    numero_definicion: 27,
    numero_prueba: 1,
    accion: "ADD",
    valor: "John123",
    codigo: "NOMBRE_FORMAT_KO",
  },
  {
    entidad: "alumnograduacion",
    campo: "nombre",
    numero_definicion: 28,
    numero_prueba: 1,
    accion: "ADD",
    valor: "Juan",
    codigo: true,
  },

  // NOMBRE - EDIT
  {
    entidad: "alumnograduacion",
    campo: "nombre",
    numero_definicion: 29,
    numero_prueba: 1,
    accion: "EDIT",
    valor: "A",
    codigo: "NOMBRE_MIN_SIZE_KO",
  },
  {
    entidad: "alumnograduacion",
    campo: "nombre",
    numero_definicion: 30,
    numero_prueba: 1,
    accion: "EDIT",
    valor: "A".repeat(26),
    codigo: "NOMBRE_MAX_SIZE_KO",
  },
  {
    entidad: "alumnograduacion",
    campo: "nombre",
    numero_definicion: 31,
    numero_prueba: 1,
    accion: "EDIT",
    valor: "John123",
    codigo: "NOMBRE_FORMAT_KO",
  },
  {
    entidad: "alumnograduacion",
    campo: "nombre",
    numero_definicion: 32,
    numero_prueba: 1,
    accion: "EDIT",
    valor: "Juan",
    codigo: true,
  },
  {
    entidad: "alumnograduacion",
    campo: "nombre",
    numero_definicion: 33,
    numero_prueba: 1,
    accion: "EDIT",
    valor: "",
    codigo: true,
  },

  // NOMBRE - SEARCH
  {
    entidad: "alumnograduacion",
    campo: "nombre",
    numero_definicion: 34,
    numero_prueba: 1,
    accion: "SEARCH",
    valor: "",
    codigo: true,
  },
  {
    entidad: "alumnograduacion",
    campo: "nombre",
    numero_definicion: 35,
    numero_prueba: 1,
    accion: "SEARCH",
    valor: "A".repeat(26),
    codigo: "NOMBRE_MAX_SIZE_KO",
  },
  {
    entidad: "alumnograduacion",
    campo: "nombre",
    numero_definicion: 36,
    numero_prueba: 1,
    accion: "SEARCH",
    valor: "John123",
    codigo: "NOMBRE_FORMAT_KO",
  },
  {
    entidad: "alumnograduacion",
    campo: "nombre",
    numero_definicion: 37,
    numero_prueba: 1,
    accion: "SEARCH",
    valor: "Juan",
    codigo: true,
  },

  // APELLIDOS - ADD
  {
    entidad: "alumnograduacion",
    campo: "apellidos",
    numero_definicion: 38,
    numero_prueba: 1,
    accion: "ADD",
    valor: "A",
    codigo: "APELLIDOS_MIN_SIZE_KO",
  },
  {
    entidad: "alumnograduacion",
    campo: "apellidos",
    numero_definicion: 39,
    numero_prueba: 1,
    accion: "ADD",
    valor: "A".repeat(36),
    codigo: "APELLIDOS_MAX_SIZE_KO",
  },
  {
    entidad: "alumnograduacion",
    campo: "apellidos",
    numero_definicion: 40,
    numero_prueba: 1,
    accion: "ADD",
    valor: "Smith123",
    codigo: "APELLIDOS_FORMAT_KO",
  },
  {
    entidad: "alumnograduacion",
    campo: "apellidos",
    numero_definicion: 41,
    numero_prueba: 1,
    accion: "ADD",
    valor: "Smith",
    codigo: true,
  },

  // APELLIDOS - EDIT
  {
    entidad: "alumnograduacion",
    campo: "apellidos",
    numero_definicion: 42,
    numero_prueba: 1,
    accion: "EDIT",
    valor: "A",
    codigo: "APELLIDOS_MIN_SIZE_KO",
  },
  {
    entidad: "alumnograduacion",
    campo: "apellidos",
    numero_definicion: 43,
    numero_prueba: 1,
    accion: "EDIT",
    valor: "A".repeat(36),
    codigo: "APELLIDOS_MAX_SIZE_KO",
  },
  {
    entidad: "alumnograduacion",
    campo: "apellidos",
    numero_definicion: 44,
    numero_prueba: 1,
    accion: "EDIT",
    valor: "Smith123",
    codigo: "APELLIDOS_FORMAT_KO",
  },
  {
    entidad: "alumnograduacion",
    campo: "apellidos",
    numero_definicion: 45,
    numero_prueba: 1,
    accion: "EDIT",
    valor: "Smith",
    codigo: true,
  },
  {
    entidad: "alumnograduacion",
    campo: "apellidos",
    numero_definicion: 46,
    numero_prueba: 1,
    accion: "EDIT",
    valor: "",
    codigo: true,
  },

  // APELLIDOS - SEARCH
  {
    entidad: "alumnograduacion",
    campo: "apellidos",
    numero_definicion: 47,
    numero_prueba: 1,
    accion: "SEARCH",
    valor: "",
    codigo: true,
  },
  {
    entidad: "alumnograduacion",
    campo: "apellidos",
    numero_definicion: 48,
    numero_prueba: 1,
    accion: "SEARCH",
    valor: "A".repeat(36),
    codigo: "APELLIDOS_MAX_SIZE_KO",
  },
  {
    entidad: "alumnograduacion",
    campo: "apellidos",
    numero_definicion: 49,
    numero_prueba: 1,
    accion: "SEARCH",
    valor: "Smith123",
    codigo: "APELLIDOS_FORMAT_KO",
  },
  {
    entidad: "alumnograduacion",
    campo: "apellidos",
    numero_definicion: 50,
    numero_prueba: 1,
    accion: "SEARCH",
    valor: "Smith",
    codigo: true,
  },

  // TITULACION - ADD
  {
    entidad: "alumnograduacion",
    campo: "titulacion",
    numero_definicion: 51,
    numero_prueba: 1,
    accion: "ADD",
    valor: "",
    codigo: "TITULACION_EMPTY_KO",
  },
  {
    entidad: "alumnograduacion",
    campo: "titulacion",
    numero_definicion: 52,
    numero_prueba: 1,
    accion: "ADD",
    valor: "MBA",
    codigo: "TITULACION_INVALID_KO",
  },
  {
    entidad: "alumnograduacion",
    campo: "titulacion",
    numero_definicion: 53,
    numero_prueba: 1,
    accion: "ADD",
    valor: "GREI",
    codigo: true,
  },

  // TITULACION - EDIT
  {
    entidad: "alumnograduacion",
    campo: "titulacion",
    numero_definicion: 54,
    numero_prueba: 1,
    accion: "EDIT",
    valor: "MBA",
    codigo: "TITULACION_INVALID_KO",
  },
  {
    entidad: "alumnograduacion",
    campo: "titulacion",
    numero_definicion: 55,
    numero_prueba: 1,
    accion: "EDIT",
    valor: "MEI",
    codigo: true,
  },
  {
    entidad: "alumnograduacion",
    campo: "titulacion",
    numero_definicion: 56,
    numero_prueba: 1,
    accion: "EDIT",
    valor: "",
    codigo: true,
  },

  // TITULACION - SEARCH
  {
    entidad: "alumnograduacion",
    campo: "titulacion",
    numero_definicion: 57,
    numero_prueba: 1,
    accion: "SEARCH",
    valor: "",
    codigo: true,
  },
  {
    entidad: "alumnograduacion",
    campo: "titulacion",
    numero_definicion: 58,
    numero_prueba: 1,
    accion: "SEARCH",
    valor: "GREIA",
    codigo: "TITULACION_MAX_SIZE_KO",
  },

  // DNI - ADD
  {
    entidad: "alumnograduacion",
    campo: "dni",
    numero_definicion: 59,
    numero_prueba: 1,
    accion: "ADD",
    valor: "",
    codigo: "DNI_VACIO_KO",
  },
  {
    entidad: "alumnograduacion",
    campo: "dni",
    numero_definicion: 60,
    numero_prueba: 1,
    accion: "ADD",
    valor: "1234567",
    codigo: "DNI_FORMATO_KO",
  },
  {
    entidad: "alumnograduacion",
    campo: "dni",
    numero_definicion: 61,
    numero_prueba: 1,
    accion: "ADD",
    valor: "A1234567L",
    codigo: "NIE_FORMATO_KO",
  },
  {
    entidad: "alumnograduacion",
    campo: "dni",
    numero_definicion: 62,
    numero_prueba: 1,
    accion: "ADD",
    valor: "12345678A",
    codigo: "DNI_LETRA_KO",
  },
  {
    entidad: "alumnograduacion",
    campo: "dni",
    numero_definicion: 63,
    numero_prueba: 1,
    accion: "ADD",
    valor: "12345678Z",
    codigo: true,
  },

  // DNI - EDIT
  {
    entidad: "alumnograduacion",
    campo: "dni",
    numero_definicion: 64,
    numero_prueba: 1,
    accion: "EDIT",
    valor: "1234567",
    codigo: "DNI_FORMATO_KO",
  },
  {
    entidad: "alumnograduacion",
    campo: "dni",
    numero_definicion: 65,
    numero_prueba: 1,
    accion: "EDIT",
    valor: "12345678Z",
    codigo: true,
  },
  {
    entidad: "alumnograduacion",
    campo: "dni",
    numero_definicion: 66,
    numero_prueba: 1,
    accion: "EDIT",
    valor: "",
    codigo: true,
  },

  // DNI - SEARCH
  {
    entidad: "alumnograduacion",
    campo: "dni",
    numero_definicion: 67,
    numero_prueba: 1,
    accion: "SEARCH",
    valor: "",
    codigo: true,
  },
  {
    entidad: "alumnograduacion",
    campo: "dni",
    numero_definicion: 68,
    numero_prueba: 1,
    accion: "SEARCH",
    valor: "1234567",
    codigo: "DNI_FORMATO_KO",
  },
  {
    entidad: "alumnograduacion",
    campo: "dni",
    numero_definicion: 69,
    numero_prueba: 1,
    accion: "SEARCH",
    valor: "12345678Z",
    codigo: true,
  },

  // TELEFONO - ADD
  {
    entidad: "alumnograduacion",
    campo: "telefono",
    numero_definicion: 70,
    numero_prueba: 1,
    accion: "ADD",
    valor: "12345",
    codigo: "TELEFONO_MIN_SIZE_KO",
  },
  {
    entidad: "alumnograduacion",
    campo: "telefono",
    numero_definicion: 71,
    numero_prueba: 1,
    accion: "ADD",
    valor: "6123456789",
    codigo: true,
  },
  {
    entidad: "alumnograduacion",
    campo: "telefono",
    numero_definicion: 72,
    numero_prueba: 1,
    accion: "ADD",
    valor: "61234abcd9",
    codigo: "TELEFONO_FORMAT_KO",
  },

  // TELEFONO - EDIT
  {
    entidad: "alumnograduacion",
    campo: "telefono",
    numero_definicion: 73,
    numero_prueba: 1,
    accion: "EDIT",
    valor: "",
    codigo: true,
  },
  {
    entidad: "alumnograduacion",
    campo: "telefono",
    numero_definicion: 74,
    numero_prueba: 1,
    accion: "EDIT",
    valor: "12345",
    codigo: "TELEFONO_MIN_SIZE_KO",
  },
  {
    entidad: "alumnograduacion",
    campo: "telefono",
    numero_definicion: 75,
    numero_prueba: 1,
    accion: "EDIT",
    valor: "61234abcd9",
    codigo: "TELEFONO_FORMAT_KO",
  },
  {
    entidad: "alumnograduacion",
    campo: "telefono",
    numero_definicion: 76,
    numero_prueba: 1,
    accion: "EDIT",
    valor: "6123456789",
    codigo: true,
  },

  // TELEFONO - SEARCH
  {
    entidad: "alumnograduacion",
    campo: "telefono",
    numero_definicion: 77,
    numero_prueba: 1,
    accion: "SEARCH",
    valor: "",
    codigo: true,
  },
  {
    entidad: "alumnograduacion",
    campo: "telefono",
    numero_definicion: 78,
    numero_prueba: 1,
    accion: "SEARCH",
    valor: "6123456789",
    codigo: true,
  },
  {
    entidad: "alumnograduacion",
    campo: "telefono",
    numero_definicion: 79,
    numero_prueba: 1,
    accion: "SEARCH",
    valor: "61234abcd9",
    codigo: "TELEFONO_FORMAT_KO",
  },

  // DIRECCION - ADD
  {
    entidad: "alumnograduacion",
    campo: "direccion",
    numero_definicion: 80,
    numero_prueba: 1,
    accion: "ADD",
    valor: "",
    codigo: "DIRECCION_VACIA_KO",
  },
  {
    entidad: "alumnograduacion",
    campo: "direccion",
    numero_definicion: 81,
    numero_prueba: 1,
    accion: "ADD",
    valor: "Calle Mayor 1, Madrid",
    codigo: true,
  },

  // DIRECCION - EDIT
  {
    entidad: "alumnograduacion",
    campo: "direccion",
    numero_definicion: 82,
    numero_prueba: 1,
    accion: "EDIT",
    valor: "",
    codigo: true,
  },
  {
    entidad: "alumnograduacion",
    campo: "direccion",
    numero_definicion: 83,
    numero_prueba: 1,
    accion: "EDIT",
    valor: "Calle Mayor 1, Madrid",
    codigo: true,
  },

  // DIRECCION - SEARCH
  {
    entidad: "alumnograduacion",
    campo: "direccion",
    numero_definicion: 84,
    numero_prueba: 1,
    accion: "SEARCH",
    valor: "",
    codigo: true,
  },
  {
    entidad: "alumnograduacion",
    campo: "direccion",
    numero_definicion: 85,
    numero_prueba: 1,
    accion: "SEARCH",
    valor: "Calle Mayor 1, Madrid",
    codigo: true,
  },

  // EMAIL - ADD
  {
    entidad: "alumnograduacion",
    campo: "email",
    numero_definicion: 86,
    numero_prueba: 1,
    accion: "ADD",
    valor: "",
    codigo: "EMAIL_VACIO_KO",
  },
  {
    entidad: "alumnograduacion",
    campo: "email",
    numero_definicion: 87,
    numero_prueba: 1,
    accion: "ADD",
    valor: "usuario@dominio",
    codigo: "EMAIL_FORMAT_KO",
  },
  {
    entidad: "alumnograduacion",
    campo: "email",
    numero_definicion: 88,
    numero_prueba: 1,
    accion: "ADD",
    valor: "usuario@dominio.com",
    codigo: true,
  },

  // EMAIL - EDIT
  {
    entidad: "alumnograduacion",
    campo: "email",
    numero_definicion: 89,
    numero_prueba: 1,
    accion: "EDIT",
    valor: "",
    codigo: true,
  },
  {
    entidad: "alumnograduacion",
    campo: "email",
    numero_definicion: 90,
    numero_prueba: 1,
    accion: "EDIT",
    valor: "usuario@dominio",
    codigo: "EMAIL_FORMAT_KO",
  },
  {
    entidad: "alumnograduacion",
    campo: "email",
    numero_definicion: 91,
    numero_prueba: 1,
    accion: "EDIT",
    valor: "usuario@dominio.com",
    codigo: true,
  },

  // EMAIL - SEARCH
  {
    entidad: "alumnograduacion",
    campo: "email",
    numero_definicion: 92,
    numero_prueba: 1,
    accion: "SEARCH",
    valor: "",
    codigo: true,
  },
  {
    entidad: "alumnograduacion",
    campo: "email",
    numero_definicion: 93,
    numero_prueba: 1,
    accion: "SEARCH",
    valor: "usuario@dominio",
    codigo: "EMAIL_FORMAT_KO",
  },
  {
    entidad: "alumnograduacion",
    campo: "email",
    numero_definicion: 94,
    numero_prueba: 1,
    accion: "SEARCH",
    valor: "usuario@dominio.com",
    codigo: true,
  },
];

const alumnograduacion_tests_files = [
  // FOTOACTO - ADD
  {
    entidad: "alumnograduacion",
    campo: "fotoacto",
    numero_definicion: 1,
    numero_prueba: 1,
    accion: "ADD",
    parametro: "max_size_file",
    valor: "6MB",
    codigo: "FILE_MAX_SIZE_KO",
  },
  {
    entidad: "alumnograduacion",
    campo: "fotoacto",
    numero_definicion: 2,
    numero_prueba: 1,
    accion: "ADD",
    parametro: "type_file",
    valor: "exe",
    codigo: "FILE_TYPE_KO",
  },
  {
    entidad: "alumnograduacion",
    campo: "fotoacto",
    numero_definicion: 3,
    numero_prueba: 1,
    accion: "ADD",
    parametro: "format_name_file",
    valor: "foto_acto_20251010.doc",
    codigo: "FILE_NAME_FORMAT_KO",
  },
  {
    entidad: "alumnograduacion",
    campo: "fotoacto",
    numero_definicion: 4,
    numero_prueba: 1,
    accion: "ADD",
    parametro: "max_size_file",
    valor: "2MB",
    codigo: true,
  },
  {
    entidad: "alumnograduacion",
    campo: "fotoacto",
    numero_definicion: 5,
    numero_prueba: 1,
    accion: "ADD",
    parametro: "type_file",
    valor: "jpg",
    codigo: true,
  },
  {
    entidad: "alumnograduacion",
    campo: "fotoacto",
    numero_definicion: 6,
    numero_prueba: 1,
    accion: "ADD",
    parametro: "format_name_file",
    valor: "foto_acto_20251010.jpg",
    codigo: true,
  },

  // FOTOACTO - EDIT
  {
    entidad: "alumnograduacion",
    campo: "fotoacto",
    numero_definicion: 7,
    numero_prueba: 1,
    accion: "EDIT",
    parametro: "max_size_file",
    valor: "6MB",
    codigo: "FILE_MAX_SIZE_KO",
  },
  {
    entidad: "alumnograduacion",
    campo: "fotoacto",
    numero_definicion: 8,
    numero_prueba: 1,
    accion: "EDIT",
    parametro: "type_file",
    valor: "exe",
    codigo: "FILE_TYPE_KO",
  },
  {
    entidad: "alumnograduacion",
    campo: "fotoacto",
    numero_definicion: 9,
    numero_prueba: 1,
    accion: "EDIT",
    parametro: "format_name_file",
    valor: "fotoacto.doc",
    codigo: "FILE_NAME_FORMAT_KO",
  },
  {
    entidad: "alumnograduacion",
    campo: "fotoacto",
    numero_definicion: 10,
    numero_prueba: 1,
    accion: "EDIT",
    parametro: "max_size_file",
    valor: "2MB",
    codigo: true,
  },
  {
    entidad: "alumnograduacion",
    campo: "fotoacto",
    numero_definicion: 11,
    numero_prueba: 1,
    accion: "EDIT",
    parametro: "type_file",
    valor: "png",
    codigo: true,
  },
  {
    entidad: "alumnograduacion",
    campo: "fotoacto",
    numero_definicion: 12,
    numero_prueba: 1,
    accion: "EDIT",
    parametro: "format_name_file",
    valor: "fotoacto.png",
    codigo: true,
  },

  // FOTOACTO - SEARCH
  {
    entidad: "alumnograduacion",
    campo: "fotoacto",
    numero_definicion: 13,
    numero_prueba: 1,
    accion: "SEARCH",
    parametro: "max_size_file",
    valor: "2MB",
    codigo: true,
  },
  {
    entidad: "alumnograduacion",
    campo: "fotoacto",
    numero_definicion: 14,
    numero_prueba: 1,
    accion: "SEARCH",
    parametro: "type_file",
    valor: "jpg",
    codigo: true,
  },
  {
    entidad: "alumnograduacion",
    campo: "fotoacto",
    numero_definicion: 15,
    numero_prueba: 1,
    accion: "SEARCH",
    parametro: "format_name_file",
    valor: "fotoacto.jpg",
    codigo: true,
  },
];
  
